VM_SKIP_LIST=
# govmomi setting
GOVMOMI_URL=
GOVMOMI_USERNAME=
GOVMOMI_PASSWORD=
GOVMOMI_INSECURE=true

VDDK_INIT_IMAGE=
VMWARE_HOST=${GOVMOMI_URL}
VMWARE_USERNAME=${GOVMOMI_USERNAME}
VMWARE_PASSWORD=${GOVMOMI_PASSWORD}
STORAGE_CLASS=
#PROVIDER_NAME=vmware80
#PROVIDER_SECRET_NAME=vmware80-secret
#STORAGE_MAP_NAME=storagemap80
#NETWORK_MAP_NAME=storagemap80
#MIGRATION_PLAN_NAME=migplan80
#MIGRATION_NAME=migrationtest80

PROVIDER_NAME=vmware70
PROVIDER_SECRET_NAME=vmware70-secret
STORAGE_MAP_NAME=storagemap70
NETWORK_MAP_NAME=storagemap70
MIGRATION_PLAN_NAME=migplan70
MIGRATION_NAME=migrationtest70
TARGET_NAMESPACE=default
MIGRATION_VMS=

REPLACE_VARS=(__PROVIDER_NAME__
    __VDDK_INIT_IMAGE__
    __PROVIDER_SECRET_NAME__
    __VMWARE_HOST__
    __VMWARE_USERNAME__
    __VMWARE_PASSWORD__
    __THUMBPRINT__
    __STORAGE_MAP_NAME__
    __NETWORK_MAP_NAME__
    __MIGRATION_PLAN_NAME__
    __TARGET_NAMESPACE__
    __MIGRATION_NAME__
)
