apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  annotations:
    forklift.konveyor.io/shared: "true"
  name: __STORAGE_MAP_NAME__
  namespace: openshift-mtv
spec:
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: __PROVIDER_NAME__
      namespace: openshift-mtv
  map:
  # append the storage maps by script
